development:
  url: 'http://localhost:3000'
  from_email: 'example.email.for.diploma@mail.ru'
production:
  url: 'http://taxistation.herokuapp.com'
  from_email: 'example.email.for.diploma@mail.ru'
test:
  url: 'http://localhost:3000'
  from_email: 'example.email.for.diploma@mail.ru'
